version: '3.3'

services:
  cpanel:
    build: .
    command: >
      sh -c "
        nginx -g 'daemon off;'"
    expose:
        - 8083
    volumes:
        - ./app:/usr/share/nginx/html
    ports:
      - "8083:8083"
